name: My First Workflow

on: push 

jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      
      - name: List and Read File
        run: 
          echo "My First Github Actions Job"
          ls
          cat README.md

      - name: Genaerate ASCII Artwork
        run: cowsay "Hello from GitHub Actions!"


    
